# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACRUsername: 'acremploistp4'
  ACRPassword: 'j9DdcGcuSxIrKAQuepNJjWXUl7HM/GJKtkH/heiCYy+ACRCuy5uj'
  ACRName: 'acremploistp4'
  ACRResourceGroup: 'rg-TP4-DevInfo'
  APIName: 'emplois-api'
  ContainerImage: 'acremploistp4.azurecr.io/modernrecrutemploisapi:latest'
  DNSLabel: 'emplois-api-depnuagtp4-jgnj'

jobs:
- job: BuildAndDeploy
  steps:
  - task: Docker@2
    displayName: 'Docker Login'
    inputs:
      command: 'login'
      containerRegistry: 'sc-dr-tp4-jgnj'
      username: $(ACRUsername)
      password: $(ACRPassword)  

  - script: docker pull $(ContainerImage)
    displayName: 'Docker Pull'    


  - script: |
      az login --tenant 1605ff27-7b8c-4c88-8e77-5f1e3c837875
      az container create --resource-group $(ACRResourceGroup) --name $(APIName) --image $(ContainerImage) --cpu 0.75 --memory 2 --registry-username $(ACRUsername) --registry-password $(ACRPassword) --dns-name-label $(DNSLabel) --ports 80
    displayName: 'Create Azure Container Instance'
