
# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACRUsername: 'acrTP4jgnj'
  ACRPassword: 'Dju95aZWDJNERaJnpH6Tn4MDjKdLLSHtPQLT8iLypd+ACRCEjREI'
  ACRName: 'acrTP4jgnj'
  ACRResourceGroup: 'rg-TP4-JG_NJ'
  APIName: 'Emplois-API'
  ContainerImage: 'acrtp4jgnj.azurecr.io/modernrecrutemploisapi:latest'
  DNSLabel: 'emplois-api-depnuagtp4-jgnj'

jobs:
- job: BuildAndDeploy
  steps:
  - task: Docker@2
    displayName: 'Docker Login'
    inputs:
      command: 'login'
      containerRegistry: 'acrtp4jgnj.azurecr.io'
      username: $(ACRUsername)
      password: $(ACRPassword)

  - task: Docker@2
    displayName: 'Docker Pull'
    inputs:
      command: 'pull'
      containerRegistry: 'acrtp4jgnj.azurecr.io'
      repository: 'modernrecrutemploisapi'
      tag: 'latest'

  - script: |
      az container create --resource-group $(ACRResourceGroup) --name $(APIName) --image $(ContainerImage) --cpu 0.75 --memory 1.5Gi --registry-username $(ACRUsername) --registry-password $(ACRPassword) --dns-name-label $(DNSLabel) --ports 80
    displayName: 'Create Azure Container Instance'

